name: 编译魔改Readest离线版
on: push
jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: 下载trae.zip源码包
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: ook826092-cloud/my-readest-offline
          tag: 1.0
          file: trae.zip

      - name: 解压源码
        run: unzip trae.zip

      - name: 安装系统依赖
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev build-essential curl libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev patchelf

      - uses: actions-rs/toolchain@v1
        with: {toolchain: stable}
      - uses: actions/setup-node@v4
        with: {node-version: 20}
      - run: npm install -g pnpm

      - run: pnpm install
      - name: 编译安卓APK
        env:
          NODE_OPTIONS: "--max-old-space-size=14336"
        run: cargo install tauri-cli && cargo tauri android build --release

      - uses: actions/upload-artifact@v4
        with:
          name: 魔改离线版Readest
          path: target/android/release/apk/release/*.apk
